name: Android

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/Archlinux.yml'
      - '.github/workflows/Windows.yml'
      - '.github/workflows/macOS.yml'
      - '.github/workflows/iOS.yml'
      - '.github/workflows/Ubuntu.yml'
      - '.github/workflows/Fedora.yml'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/Archlinux.yml'
      - '.github/workflows/Windows.yml'
      - '.github/workflows/macOS.yml'
      - '.github/workflows/iOS.yml'
      - '.github/workflows/Ubuntu.yml'
      - '.github/workflows/Fedora.yml'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

jobs:
  build:
    name: Android-${{ matrix.arch }} ( ${{ matrix.kind }}-${{ matrix.mode }} )

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        kind: [static, shared]
        mode: [release, debug, asan]
        arch: [armeabi-v7a, arm64-v8a]

    runs-on: ${{ matrix.os }}

    concurrency:
      group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-Android-${{ matrix.arch }}-${{ matrix.kind }}-${{ matrix.mode }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup XMake cache
        uses: actions/cache@v3
        if: ${{ !env.ACT }}
        with:
          path: '.xmake-cache'
          key: ${{ matrix.os }}-ci

      - name: Install xmake (cached)
        uses: xmake-io/github-action-setup-xmake@v1
        if: ${{ !env.ACT }}
        with:
          xmake-version: branch@dev
          actions-cache-folder: '.xmake-cache'
          actions-cache-key: '${{ matrix.os }}-ci'

      - name: Install xmake
        uses: xmake-io/github-action-setup-xmake@v1
        if: ${{ env.ACT }}
        with:
          xmake-version: branch@dev

      - name: Update xmake repository
        run: xmake repo --update

      - name: Prepare
        run: |
          wget -q https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip -q -o ./android-ndk-r25b-linux.zip

      - name: Configure & Build
        id: build
        run: |
          xmake f -D --yes -a ${{ matrix.arch }} -p android --ndk=`pwd`/android-ndk-r25b --ndk_sdkver=33 -m ${{ matrix.mode }} -k ${{ matrix.kind }} --build_tests=false
          xmake b -D

      - name: Installation
        run: xmake install -D --installdir="${{ runner.workspace }}/output"

      - name: Upload artifacts
        id: upload
        uses: actions/upload-artifact@v1
        with:
          name: Android-${{ matrix.arch }}-${{ matrix.kind }}-${{ matrix.mode }}
          path: ${{ runner.workspace }}/output
