name: Fedora

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/Archlinux.yml'
      - '.github/workflows/Ubuntu.yml'
      - '.github/workflows/Windows.yml'
      - '.github/workflows/macOS.yml'
      - '.github/workflows/iOS.yml'
      - '.github/workflows/Android.yml'
      - '.github/workflows/FreeBSD.yml'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/Archlinux.yml'
      - '.github/workflows/Ubuntu.yml'
      - '.github/workflows/Windows.yml'
      - '.github/workflows/macOS.yml'
      - '.github/workflows/iOS.yml'
      - '.github/workflows/Android.yml'
      - '.github/workflows/FreeBSD.yml'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

jobs:
  build:
    name: fedora-latest-x64 ( ${{ matrix.kind }}-${{ matrix.mode }} )

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        kind: [static, shared]
        mode: [release, debug, asan]

    runs-on: ${{ matrix.os }}
    container:
        image: fedora:latest
        volumes:
          - /output:/output

    concurrency:
      group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-Fedora-${{ matrix.kind }}-${{ matrix.mode }}

    steps:
      - name: Dependencies bootstrap
        run: |
          dnf -y install @development-tools @rpm-development-tools
          dnf -y install copr-cli make gcc-c++ libatomic
          dnf -y upgrade git
          dnf -y install perl
          dnf -y install glibc-static libstdc++-static libasan
          dnf -y install gfortran

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@dev

      - name: Update xmake repository
        run: sudo /__t/xmake/dev/x64/bin/xmake repo --root -vD --update

      - name: Configure & Build
        id: build
        run: |
          sudo /__t/xmake/dev/x64/bin/xmake f --root -vD --yes -m ${{ matrix.mode }} -k ${{ matrix.kind }} --build_tests=true
          sudo /__t/xmake/dev/x64/bin/xmake b --root -vD
          sudo /__t/xmake/dev/x64/bin/xmake install --root -vD --installdir="/output"

      - name: Tests
        run: sudo /__t/xmake/dev/x64/bin/xmake run --root glap-tests

      - name: Upload artifacts
        id: upload
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}-x64-${{ matrix.kind }}-${{ matrix.mode }}
          path: /output
