name: macOS

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/Archlinux.yml'
      - '.github/workflows/Windows.yml'
      - '.github/workflows/Fedora.yml'
      - '.github/workflows/iOS.yml'
      - '.github/workflows/Android.yml'
      - '.github/workflows/Ubuntu.yml'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/Archlinux.yml'
      - '.github/workflows/Windows.yml'
      - '.github/workflows/Fedora.yml'
      - '.github/workflows/iOS.yml'
      - '.github/workflows/Android.yml'
      - '.github/workflows/Ubuntu.yml'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

jobs:
  build:
    name: ${{ matrix.os }}-x64 ( ${{ matrix.kind }}-${{ matrix.mode }} )

    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest]
        kind: [static, shared]
        mode: [release, debug, asan]

    runs-on: ${{ matrix.os }}

    concurrency:
      group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-macOS-${{ matrix.kind }}-${{ matrix.mode }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup XMake cache
        uses: actions/cache@v3
        with:
          path: '.xmake-cache'
          key: ${{ matrix.os }}-ci

      - name: Install xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@dev
          actions-cache-folder: '.xmake-cache'
          actions-cache-key: '${{ matrix.os }}-ci'

      - name: Update xmake repository
        run: xmake repo --update

      - name: Configure & Build
        id: build
        run: |
          xmake f -D --yes -m ${{ matrix.mode }} -k ${{ matrix.kind }} --build_tests=false
          xmake b -D

      - name: Installation
        run: xmake install -D --installdir="${{ runner.workspace }}/output"

      - name: Upload artifacts
        id: upload
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}-x64-${{ matrix.kind }}-${{ matrix.mode }}
          path: ${{ runner.workspace }}/output
