name: Windows

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/Archlinux.yml'
      - '.github/workflows/Ubuntu.yml'
      - '.github/workflows/Fedora.yml'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/Archlinux.yml'
      - '.github/workflows/Ubuntu.yml'
      - '.github/workflows/Fedora.yml'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

jobs:
  build:
    name: ${{ matrix.os }}-${{ matrix.arch }} ( ${{ matrix.kind }}-${{ matrix.mode }}-{{ matrix.vs_runtime }} )

    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022]
        kind: [static, shared]
        mode: [release, debug, asan]
        vs_runtime: [MT, MD]
        arch: [x64, arm64]

    runs-on: ${{ matrix.os }}

    concurrency:
      group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-Windows-${{ matrix.kind }}-${{ matrix.mode }}-{{ matrix.vs_runtime }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@dev

      - name: Update xmake repository
        run: xmake repo --update

      - name: Configure Pagefile
        uses: al-cheb/configure-pagefile-action@v1.3
        with:
          minimum-size: 8GB
          maximum-size: 32GB
          disk-root: "D:"

      - name: Configure & Build
        id: build
        run: |
          xmake f -D --yes -a ${{ matrix.arch }} -m ${{ matrix.mode }} -k ${{ matrix.kind }} --vs_runtime=${{ matrix.vs_runtime }} --build_tests=true
          xmake b -D
          xmake install -D --installdir="${{ runner.workspace }}/output"

      - name: Tests
        run: xmake run glap-tests

      - name: Upload artifacts
        id: upload
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.kind }}-${{ matrix.mode }}-${{ matrix.vs_runtime }}
          path: ${{ runner.workspace }}/output
